CREATE TABLE localizacao (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    latitude float8 NULL,
    longitude float8 NULL,
    CONSTRAINT localizacao_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurante (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(50) NULL,
    localizacao_id int8 NOT NULL,
    CONSTRAINT restaurante_pkey PRIMARY KEY (id)
);

ALTER TABLE restaurante ADD CONSTRAINT res_loc FOREIGN KEY (localizacao_id) REFERENCES localizacao(id);

CREATE TABLE prato (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao varchar(200) NULL,
    nome varchar(50) NULL,
    preco numeric(19,2) NOT NULL,
    restaurante_id int8 NOT NULL
);

ALTER TABLE prato ADD CONSTRAINT prato_rest FOREIGN KEY (restaurante_id) REFERENCES restaurante(id);

CREATE TABLE prato_cliente (
    prato int,
    cliente varchar(200)
);

INSERT INTO localizacao (id, latitude, longitude) VALUES(1000, -15.817759, -42.231324);

INSERT INTO restaurante (id, localizacao_id, nome) VALUES(999, 1000, 'FReal');

INSERT INTO prato (id, nome, descricao, restaurante_id, preco) VALUES(9998, 'Poke ceviche mix base arroz', 'Arroz com ceviche mix (mix de peixe, cebola roxa, pimenta, cebolinha, limão e azeite), sunomono, couve crispy e crispy de tempurá', 999, 20.99);

INSERT INTO prato (id, nome, descricao, restaurante_id, preco) VALUES(9997, 'Temaki salmão', 'Salmão, cebolinha e cream cheese ou maionese.', 999, 22.90);